job1:
    script:
        - "cp .env.example .env"
        - "composer.phar install --prefer-source --no-interaction"
        - "/etc/init.d/mysql start"
        - "php artisan migrate --seed"
        - "php artisan assets:update"
        - "php artisan assets:build"
        - "phpunit --tap --coverage-text=/tmp/clover.txt --coverage-html=/tmp/cloverHtml"

        # code coverage extraction for gitlab-ci (workaround for phpunit --colors=false not working for text code coverage)
        - "cat /tmp/clover.txt"

        # here we can upload the html code coverage for a better review